# Generated by Django 3.1.14 on 2024-02-12 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_user', '0001_initial'),
        ('invoice', '0002_auto_20240212_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_suer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice_user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.customuser'),
            preserve_default=False,
        ),
    ]
