# Generated by Django 3.1.14 on 2024-02-12 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('select_option', '0001_initial'),
        ('invoice', '0005_auto_20240212_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='select_option.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
