# Generated by Django 3.1.14 on 2024-02-13 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_group', '0002_auto_20240208_2031'),
        ('invoice', '0006_auto_20240212_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_group.category'),
        ),
    ]
