# Generated by Django 3.1.14 on 2024-02-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_group.category'),
        ),
    ]
