# Generated by Django 3.1.14 on 2024-02-29 17:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0001_initial'),
        ('invoice_group', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='InvoiceOption',
            new_name='Option',
        ),
    ]
