# Generated by Django 3.1.14 on 2024-02-29 21:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_group', '0002_auto_20240229_1740'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('name', 'category', 'user')},
        ),
    ]
