# Generated by Django 3.1.14 on 2024-02-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_group', '0002_auto_20240208_2031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('name', 'category')},
        ),
    ]
