# Generated by Django 3.1.14 on 2024-01-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=16)),
                ('name_on_card', models.CharField(max_length=16)),
                ('card_number', models.CharField(max_length=16)),
                ('card_type', models.CharField(choices=[('master', 'Master'), ('visa', 'Visa'), ('rupay', 'Rupay')], max_length=10)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
