# Generated by Django 3.1.14 on 2024-01-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_sub_method',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
