# Generated by Django 3.1.14 on 2024-01-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_transaction_sub_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_method',
            field=models.CharField(choices=[('bank', 'Bank'), ('credit_card', 'Credit Card'), ('wallet', 'Walllet')], max_length=20),
        ),
    ]
