# Generated by Django 3.1.14 on 2024-01-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20240131_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_method',
            field=models.CharField(choices=[('bank', 'Bank'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('wallet', 'Walllet'), ('bank_upi', 'Bank UPI'), ('credit_upi', 'Credit Card UPI')], max_length=20),
        ),
    ]
