# Generated by Django 3.1.14 on 2024-02-18 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20240213_0004'),
        ('transaction', '0006_transaction_transaction_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
            preserve_default=False,
        ),
    ]
